Revert "Merge branch 'MR_prepare_dss20_sqlite3' into 'master'"
This reverts commit e3d2d068302d0acf7f395dea737f1b46c1b89b06, reversing
changes made to f69e8cce85cfe4bcd967984ab688f7ebba3bd124.

This merge broke oe build:

In file included from ../src/handler/db_fetch.cpp:29:0:
../src/sqlite3_wrapper.h:31:37: fatal error: boost/move/unique_ptr.hpp: No such file or directory
 #include <boost/move/unique_ptr.hpp>