exception: add cpp file to verify exception is independent
This ensures that header is standalone and does not depend on
any other include

Signed-off-by: Andreas Fenkart <andreas.fenkart@dev.digitalstrom.org>