device: fix -Wmissing-field-initializers
../src/model/device.cpp:662:79: error: missing field 'usage' initializer [-Werror,-Wmissing-field-initializers]
    DeviceSensorSpec_t sensorInputReserved1 = {SensorType::Reserved1, 0, 0, 0 };

Introduced in 52ecd1406b632e43a1ff578ce029f00cf0e40d27