sceneHelper: fix missing include <vector>
../src/model/scenehelper.h:66:23: error: no type named 'vector' in namespace 'std'
    static const std::vector<int>& getAvailableScenes();